#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://$localhost:3306/ecommercedb
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging:
  level:
    springframework:
      web: DEBUG
  org:
    hibernate: ERROR
management:
  endpoint:
    health:
      show-details=always:
    web:
      exposure:
        include=*:

server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: http://localhost:9092
  jpa:
    hibernate:
      ddl-auto:
        update
    jdbc:
      batch_size: 20
    cache:
      use_query_cache: false
      use_second_level_cache: false
      use_structured_entries: false
      use_minimal_puts: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tiki